spring:
  application:
    name: oauth2-demo-b-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/oauth2_demo
    username: root
    password: 123456
    druid:
      # 配置初始化连接池大小
      initial-size: 5
      # 配置初始化连接池最小连接数
      min-idle: 5
      # 配置初始化连接池最大连接数
      max-active: 100
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久进行一次检测，检测需要关闭的空闲连接，单位毫秒。
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在连接池中的最小生存时间，单位毫秒
      min-evictable-idle-time-millis: 60000
      # 配置一个连接在连接池中的最大生存时间，单位毫秒
      max-evictable-idle-time-millis: 90000
      # 用来测试连接是否可用的SQL语句
      validation-query: SELECT 1
      # 配置从连接池空闲时，是否检查连接有效性，true每次都检查；false不检查
      test-while-idle: true
      # 配置从连接池获取连接时，是否检查连接有效性，true每次都检查；false不检查
      test-on-borrow: false
      # 配置向连接池归还连接时，是否检查连接有效性，true每次都检查；false
      test-on-return: false
      # 配置监控统计拦截的filters
      # filters: stat,wall,log4j
      # 复用连接和避免短连接
      keep-alive: true
      # 设置获取连接出错时的自动重连次数, 默认1
      connection-error-retry-attempts: 1
      # true表示向数据库请求连接失败后,就算后端数据库恢复正常也不进行重连,客户端对pool的请求都拒绝掉.false表示新的请求都会尝试去数据库请求connection.默认为false
      break-after-acquire-failure: false
      filter:
        stat:
          # 开启监控统计慢查询
          log-slow-sql: true
          # 超过多少毫秒属于慢查询，默认300ms
          slow-sql-millis: 300

  # 数据库数据版本管理flyway
  flyway:
    baseline-on-migrate: true
    enabled: true
    clean-disabled: true
    table: b_flyway_history
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        min-idle: 1
        max-idle: 30
        max-active: 1000
        max-wait: 5000ms

# dubbo
dubbo:
  protocol:
    name: dubbo
    port: 20888
  registry:
    address: nacos://localhost:8848
  scan:
    base-packages: com.phper666.oauth2.demo.b.provider

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml

# 日志
logging:
  file:
    path: ./logs

